#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Create nsd database folder and setup permissions
echo "* Create nsd database folder and setup permissions"
mkdir -p /var/nsd
chown nsd:nsd /var/nsd

# Change permissions for nsd config folder
echo "* Change permissions for nsd config folder"
chown nsd:nsd /opt/local/etc/nsd

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
