#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGIN_SRC='/opt/local/lib/munin/plugins'
MUNIN_PLUGIN_DST='/opt/local/etc/munin/plugins'
MUNIN_PLUGINS=(
	'nsd_munin_hits'
	'nsd_munin_memory'
	'nsd_munin_by_type'
	'nsd_munin_by_class'
	'nsd_munin_by_opcode'
	'nsd_munin_by_rcode'
	'nsd_munin_zones'
)

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Create nsd database folder and setup permissions
echo "* Create nsd database folder and setup permissions"
mkdir -p /var/nsd
chown nsd:nsd /var/nsd

# Change permissions for nsd config folder
echo "* Change permissions for nsd config folder"
mkdir -p /opt/local/etc/nsd/core
chown -R nsd:nsd /opt/local/etc/nsd

# Import nsd manifest
echo "* Import nsd manifest"
svccfg import /tmp/nsd.xml
rm /tmp/nsd.xml

# Activate munin plugins
echo "* Activate munin plugins"
for plugin in "${MUNIN_PLUGINS[@]}"; do
	if [ ! -x ${MUNIN_PLUGIN_SRC}/${plugin} ]; then
		plugin_src=${plugin%_*}_
		[ ! -x ${MUNIN_PLUGIN_SRC}/${plugin_src} ] && \
			plugin_src=${plugin_src%%_*}_
	else
		plugin_src=${plugin}
	fi
	if [[ -x ${MUNIN_PLUGIN_SRC}/${plugin_src} ]]; then
		echo "  ${plugin}"
		ln -sf ${MUNIN_PLUGIN_SRC}/${plugin_src} ${MUNIN_PLUGIN_DST}/${plugin}
	fi
done

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
