#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	nsd_munin_hits
	nsd_munin_memory
	nsd_munin_by_type
	nsd_munin_by_class
	nsd_munin_by_opcode
	nsd_munin_by_rcode
	nsd_munin_zones
"

# Exit if any commands fail
set -o errexit

echo "* Configuring image specific packages.";

echo "* Create nsd database folder and setup permissions"
mkdir -p /var/nsd
chown nsd:nsd /var/nsd

echo "* Change permissions for nsd config folder"
chown -R nsd:nsd /opt/local/etc/nsd

echo "* Import nsd manifest"
svccfg import /tmp/nsd.xml
rm /tmp/nsd.xml

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
